### ISSUE TITLE
How to grep in archived log files ie., log.gz files?

### ISSUE THREAD

**Issue by skaluva** [tools4j/unix4j#40]
Hi,
I'm planning to use this library. But i have a requirement to grep in archived log files. Simply i need "zgrep" feature. Can i use this library to grep strings without extracting log files?

**Comment by terzerm** [comment]
Hi.
Thanks for your interest in the library.

Grep does not directly support gz files as egrep does. However you can still use Unix4j and its grep to directly grep gz files, e.g. as follows:
``
		final File tempFile = new File(System.getProperty("java.io.tmpdir"), "unix4j-zgrep.gz");
		final OutputStream gzOut = new GZIPOutputStream(new FileOutputStream(tempFile));
		Unix4j.fromString("ERROR bla\nINFO hello\nWARN world\nERROR end of file\n").toOutputStream(gzOut);
		gzOut.close();

		final InputStream gzStream = new GZIPInputStream(new FileInputStream(tempFile));
		Unix4j.from(gzStream).grep("ERROR").toStdOut();
``

**Comment by skaluva** [comment]
Will give a try and let you know if  i get any issues. Thanks a lot.
