### ISSUE TITLE
how to execute bash file and read the output

### ISSUE THREAD

**Issue by Bingi000** [tools4j/unix4j#43]
Hi,
Could you please help me in executing the bash file and load the output as string.

Regards
Rajkumar

**Comment by terzerm** [comment]
Hi Rajkumar,

You cannot run a bash file. Unix4j supports only selected commands.

Tell me which commands you want to run and I can help you translating this into unix4j syntax.

Regards,
Marco

**Comment by Bingi000** [comment]
Hi Marco,

Thank you for your response !! I am looking to execute a shell script from java program and store the output in a file/ java string.Commands in the shell script varies. 

If I need to execute series of commands in a file and store the output ,How can I do it using unix4j.

Can you share sample example Please.

Regards
Rajkumar

**Comment by terzerm** [comment]
Hi Rajkumar,

You cannot execute a bash script with Unix4j --- it is not designed for this use case.

To execute a bash script, see for instance here:
http://stackoverflow.com/questions/13707519/running-a-bash-shell-script-in-java
http://stackoverflow.com/questions/525212/how-to-run-unix-shell-script-from-java-code

Note that this only works on a unix machine. If you want to run a bash script on Windows, you can for instance install cygwin and then use the above methods.

Hope this helps.
Regards,
Marco
