### ISSUE TITLE
What is the roadmap ? Why there is not yet a 1.x version ?

### ISSUE THREAD

**Issue by slevy85** [tools4j/unix4j#44]
Thank you for this great librairy.
I was wandering what is missing for you to make a stable 1.x version.

Thank you for your concern.

**Comment by terzerm** [comment]
Hi. Thanks for your interest in the library.

It is stable since a few years.  The version number just happens to start with 0.  We are currently not actively working on the library, only bug fixes if someone finds any.

Regards
