### ISSUE TITLE
GrepTest fails due to expected ordering being different from actual ordering...

### ISSUE THREAD

**Issue by ssta** [tools4j/unix4j#47]
[org.unix4j.unix.GrepTest.txt](https://github.com/tools4j/unix4j/files/1768043/org.unix4j.unix.GrepTest.txt)

The counting seems to be correct, but the ordering is reversed.  I don't know if the ordering should be considered significant or not.

If it helps/matters:
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Apache Maven 3.5.0
Kernel:  4.13.0-36-generic (amd64)
Ubuntu 17.10
zsh 5.2
unix4j HEAD->964e5e11830c942fc1d16cf408621525d89fa327

**Comment by terzerm** [comment]
Thanks for reporting this.  Certainly the test should not fail hence I will provide a fix for this.

Happens I discovered a second bug that I am also fixing as part of this (appending sort before asserting seems not to work for some weird reason).

**Comment by terzerm** [comment]
Fixed as of version 0.5 (yet to be released).
