### ISSUE TITLE
Developer Guide

### ISSUE THREAD

**Issue by gunjanvarshney** [tools4j/unix4j#49]
Hi,

First of all congratulations on developing such a project which has (in my opinion) wide scale useage. I wanted to get some details on a developer guide if i as a developer want to develop support for some commands.

can you please guide.

**Comment by terzerm** [comment]
Hi.

Thanks for your interest in the library.

Please indicate the commands you'd be interested in implementing.  
* If it is a custom thing for your project, please use
* if it is of general interest, clone the repository and create a feature branch.  
** Then the first thing is to add a command definition and description file [here](https://github.com/tools4j/unix4j/tree/master/unix4j-core/unix4j-command/src/main/resources/command-definition)
** Also add your file to the codegen [config.fmpp](https://github.com/tools4j/unix4j/blob/master/unix4j-core/unix4j-command/src/main/resources/codegen/config.fmpp)
** Some classes will be generated.  The implementation will have to be provided as for example for the [echo command](https://github.com/tools4j/unix4j/tree/master/unix4j-core/unix4j-command/src/main/java/org/unix4j/unix/echo)
