### ISSUE TITLE
GrepOption.n not seems to be working

### ISSUE THREAD

**Issue by morad3741** [tools4j/unix4j#50]
Hi,
when trying to:

`List<String> lines = Unix4j.fromFile(logFile).grep(Grep.Options.n,"INFO ").toStringList();
`

the output not contains the line number

**Comment by terzerm** [comment]
Thanks for reporting this bug.  Indeed the line number option is currently not implemented.

I have posted a fix that will be released with the 0.5 version.

**Comment by terzerm** [comment]
Fixed as of version 0.5 (yet to be released).
