### ISSUE TITLE
Sed backreferences are based on $n, not on \n

### ISSUE THREAD

**Issue by marco-brandizi** [tools4j/unix4j#52]
Just discovered unix4j, so cool! Thanks for having developed it!

First thing I've tried is the sed 's' command with replacements based on backreferences. It works, but I spent quite a while to discover that substitution is based on [Matcher.appendReplacement](https://docs.oracle.com/javase/8/docs/api/java/util/regex/Matcher.html#appendReplacement-java.lang.StringBuffer-java.lang.String-), which means that backreferences must be in the form '$n' (e.g., `'$1'`), NOT the form `'\n'` (as in `'\1'`) as in the original sed, and as the documentation says. Not a big deal once you know, but the comments should be fixed.

**Comment by terzerm** [comment]
Hi

Thanks for your interest in the library and for reporting this bad doc.  Will fix and release asap.

Regards,
Marco

**Comment by terzerm** [comment]
Documentation has been fixed.  I will updated the online javadoc when we release the new version into maven central.

Thanks again for reporting this!
