### ISSUE TITLE
The process cannot access the file because it is being used by another process

### ISSUE THREAD

**Issue by nipunalk** [tools4j/unix4j#53]
Hi,

When I try to delete file after Unix4j.grep .it complains, file is used by another process.
 private void getTotalFilesFromControlFile(File file) {
		
		try {
		File dest=new File(file.getParentFile()+"\\copy"+file.getName());
		Files.copy(Paths.get(file.getAbsolutePath()),Paths.get( dest.getAbsolutePath()),StandardCopyOption.REPLACE_EXISTING);
		if (dest.exists() ) {

			String lines = Unix4j.grep(TOTAL_FILES, dest).toLineList();
		
		Files.delete(Paths.get(dest.getAbsolutePath()));
		} 
		
		}
		catch(Exception e) {
		System.out.println(e.getMessage());	
		}
		
	}

**Comment by terzerm** [comment]
Thanks for reporting this bug.  I will look into it and provide a fix asap.

DEV Remark: Can only be reproduced on Windows.

**Comment by terzerm** [comment]
This has been fixed on master and will be released in Version 0.6 some time soon.

**Comment by stormboomer** [comment]
I am facing the same issue at the moment. It seems that 0.5 is still the latest version available via the maven Repository.
Is there a plan on releasing Version 0.6 and pushing it to the maven Repository?

**Comment by terzerm** [comment]
I will look into releasing 0.6.
