### ISSUE TITLE
Request:  Release be built

### ISSUE THREAD

**Issue by lemming622** [tools4j/unix4j#54]
For the releases can it include the built jar, built Javadoc as a zip, and the built sources with dependencies downloaded as a zip?  This would help with implementation on systems where IT will not unlock or open up the ability for maven to download the dependencies.  This would also help with having an out of the box ready to go version of unix4j without having a user built it themselves.

**Comment by terzerm** [comment]
The requested jars are available on maven central and can be downloaded directly there:
https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.unix4j%22

**Comment by lemming622** [comment]
Can that link be included then in the release notes?

**Comment by terzerm** [comment]
There is a maven badge at the top of the page.  You can click on it.  

Maybe I'll add a more explicit download link to the README page at some point.
