### ISSUE TITLE
cd to allow Path

### ISSUE THREAD

**Issue by lemming622** [tools4j/unix4j#55]
At home and able to build the package.  When going through the documentation for cd this great tool allows cd to home, cd with file, and cd with String.  Would it be possible in a future version to also include cd with a Path?

**Comment by terzerm** [comment]
It is not currently planned to do that.  

Why don't you just do ``Path.toFile()``?

**Comment by lemming622** [comment]
Path is handled more as a path than File.  File has attributes and methods for a file like size.  Path has attributes and methods for a path like relative and temporaryDirectory.

**Comment by terzerm** [comment]
And?  I fear I fail to understand your point.  You use Path and all its methods and then call toFile() when you want to use Unix4j's cd command.

**Comment by lemming622** [comment]
I'm guessing its no different that why File is there.  You can do File.toString() and get the string result.  It's an implementation that allows the user to not have to convert the Path on call but rather internal to the method.
