### ISSUE TITLE
Question:  Usage of tool

### ISSUE THREAD

**Issue by lemming622** [tools4j/unix4j#57]
When building from sources which jar set (jar, sources, javadoc) is to be used?
The maven dependency is for command and the maven link is also for command but the code release as well as the link sent earlier [#54]  was not for just command but rather for the different packages in unix4j. I'm asking so that I can implement this at work where I think it would shine very well.  Downside is that work has link blockers turned on for non web applications.  That is why I have problems with building at work vs home.  Thank you for your time.

**Comment by terzerm** [comment]
you can just build from the top level directory:

```bash
cd unix4j
mvn clean install
```
