### ISSUE TITLE
GrepOption.lineNumber not working

### ISSUE THREAD

**Issue by segaura** [tools4j/unix4j#58]
My code has something like

Unix4j.fromFile(path).grep(GrepOption.lineNumber, EVIL_REGEX).toStdOut();

all the lines I want to match are correctly matched, but the output does not have the line number prefix at the beginning of each line

(Java 8, Windows 64bit)

**Comment by terzerm** [comment]
Thanks for using Unix4j.

Can you be a bit more specific? 
* Which version of unix4j are you using
* What is your input EVIL_REXEX ?

Best practice is to provide a unit test that reproduces the problem.

Thank you!

**Comment by terzerm** [comment]
Something is certainly not quite right with counting and line numbers --- working on a. fix.

Would still be helpful to get some more details of the test failure, or better a unit test that demonstrates the failure.

**Comment by segaura** [comment]
Sorry, I thougth I provided a test case because that was actually the only line of code :-)

    package com.mycompany.codeanalyzer;

    import org.unix4j.Unix4j;
    import org.unix4j.unix.grep.GrepOption;

    public class LineOptionTest {

	private static final String INPUT_PATH = "D:\\theFolder\\theFileName.theFileExtension";
        private static final String EVIL_REGEX = "anyStringOrRegexpITried";	

        public static void main(String[] args) {
            Unix4j.fromFile(INPUT_PATH).grep(GrepOption.lineNumber, EVIL_REGEX).toStdOut();
       }
    
    }


the file content at INPUT_PATH is

    anyStringOrRegexpITried

and the program output is

    anyStringOrRegexpITried

The real program uses the Find class that works like a charm, walking through a complete folders structure, so I tested this grep() with a great number of files and I never saw a line number in the output, so far.

**Comment by terzerm** [comment]
Test covering this case:
`GrepTest.testLineNumberWithRegex()`

**Comment by segaura** [comment]
My BIG fault.
I started from an example and included unix4j-command version 0.3 (I forgot to include pom.xml in the issue).
Moving to version 0.5 solved the issue, now line numbers are shown.

I am very sorry, the issue can be closed.
