### ISSUE TITLE
GrepOption.F.i is not seems to be working

### ISSUE THREAD

**Issue by yanyige** [tools4j/unix4j#59]
Hi, all:
When i use List<Line> lines = Unix4j.grep(Grep.Options.i.F, target, file). toLineList(); it seems to return nothing to me, while Grep.Options.i.n/while Grep.Options.n.F works well. It seems to occur problem when -F used with i

**Comment by terzerm** [comment]
Thanks for reporting this.  I will check and try to reproduce.  Btw it is best practice to always report bugs with a unit test that reproduces the problem ;-)

**Comment by terzerm** [comment]
Could not be reproduced.  Seems to be working fine, see
[GrepTest.testFixedStringWithIgnoreCase()](https://github.com/tools4j/unix4j/blob/master/unix4j-core/unix4j-command/src/test/java/org/unix4j/unix/GrepTest.java)

@yanyige Check your path argument, grep may be looking in the wrong directory and not find the file.  E.g. try with absolute path.
