### ISSUE TITLE
NO  match word and perform find and replace in sed

### ISSUE THREAD

**Issue by ianirudhrawat** [tools4j/unix4j#61]
there is Exception when we try " match word and perform find and replace ".
Eg. sed "/^hello/s/tom/jerry/g" gives "invalid sed arguments" exception .
its a functionality supported in sed

**Comment by benjwarner** [comment]
Hi there Ian,
Unfortunately the (unix4j) sed command doesn't support sequential sed commands.  e.g. a search followed by a search/replace.

Another approach might be:

`.grep("^hello).sed("s/tom/jerry/g")`

Cheers,
Ben

**Comment by ianirudhrawat** [comment]
thanks Ben , will try that
