### ISSUE TITLE
Not able to build the source from ide or mvn

### ISSUE THREAD

**Issue by ianirudhrawat** [tools4j/unix4j#62]
after downloading i tried to build the project (both ide and mvn ) but there were errors.
some files were missing eg. Sed Arguments, Grep Arguments etc.
Do we need to do some additional things after downloading the source code ...? sorry  i m new to maven and open source.

**Comment by benjwarner** [comment]
Hi there Ian,
Indeed, initially there will appear to be some files missing, as some of the source files need to be auto-generated.

To run a build which includes creating the missing files, try running `mvn install`.

Out of interest, are you looking to use unix4j as a utility in your own application?  Or are you just interested in having a look at the unix4j code?  

Cheers,
Ben

**Comment by ianirudhrawat** [comment]
i tried mvn install but the build process failed....
right now..i m only trying to understand  the code

**Comment by benjwarner** [comment]
Could you please paste into a reply, the the output of maven when it fails?  With an preceeding errors.

**Comment by ianirudhrawat** [comment]
[unix4jLogs.txt](https://github.com/tools4j/unix4j/files/2917518/unix4jLogs.txt)
here are the errors that i get after running "mvn clean install"

**Comment by terzerm** [comment]
Are you using java8?  And which version of maven?  We have no problems building, see also
https://travis-ci.org/github/tools4j/unix4j
