### ISSUE TITLE
Method to generate lines before and after grep match

### ISSUE THREAD

**Issue by KAyyagari2020** [tools4j/unix4j#73]
Is there a method to get lines before and after grep match in unix4j ? i.e., a java equivalent to 
**grep -B 5 -A 2  'keyword' /path/to/file.txt**

**Comment by terzerm** [comment]
Thanks for your interest in unix4j, and sorry for the late response.
Unfortunately this is not currently supported by the unix4j version of grep, and there are no immediate plans to add this option.
